name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_UPDATED_DATE: "True"
          LOCALE: "zh"
          COMMIT_BY_TIME: "True"
          SHOW_TOTAL: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          LANG_COUNT: "10"
          SYMBOL_VERSION: "3"
          SHOW_WORKING_TIME_RANGE: "True"
          WORKING_TIME_RANGE_TEXT: |
            清晨工作达人:5:00-12:00
            全天无休战士:ALL
            晚间编程客:18:00-24:00
            深夜码农:0:00-5:00
          DAY_NAMES: |
            周日
            周一
            周二
            周三
            周四
            周五
            周六
          MOST_PRODUCTIVE_DAY_TEXT: "%%DAY_NAME%%"